#!/usr/bin/env python2.7

"""
A lightweight compile and simulate script
"""

########################################################################################
# Globals

__version__       = '0.0'
__author__        = "Brian Hunter"
__email__         = 'brian.hunter@cavium.com'


#######################################################################################
# Imports
import argparse
import logging
import cn_logging
import gvars
import sge_tools as sge

Log = None

########################################################################################
def parse_args():
    """
    Parse Command-Line and return the gadgets to be run as a list of strings.
    """

    global Log

    gvars.Log = cn_logging.getLogger('gogo.log')
    gvars.Log.setLevel(logging.INFO)

    # create the handler
    console = logging.StreamHandler()
    console.setFormatter(cn_logging.formatter)
    gvars.Log.addHandler(console)

    Log = gvars.Log
    sge.Log = gvars.Log

    p = argparse.ArgumentParser(
        prog='gogo',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        usage="%(prog)s [gadgets] [options]",
        version=("%(prog)s v"+__version__),
        description=__doc__)

    p.add_argument('gadgets',        action='store', nargs='*',  help="Any one of (b)uild, (s)imulate, (p)artition, (c)lean, or help")

    p.add_argument('--test', '-t',   action='store',             default='basic', help="Specify UVM test name [default:basic]")
    p.add_argument('--dir',  '-d',   action='store',             default=None,    help="Specify alternate directory for results.")
    p.add_argument('--verb', '-V',   action='store',             default=0,       help="Specify UVM Verbosity.")
    p.add_argument('--tb',           action='store',             default='tb',    help="Specify a different tb.py configuration file.")
    p.add_argument('--interactive',  action='store_true',        default=False,   help="Run the simulation interactively.")

    p.add_argument('--simopts',      action='store',             default=None,    help="Add simulation opts as a string to simulator command-line.")
    p.add_argument('--cmpopts',      action='store',             default=None,    help="Add compilation opts as a string to compiler command-line.")
    p.add_argument('--seed', '-s',   action='store', type=int,   default=1,       help="Run with the given seed (0 for a random seed).")

    p.add_argument('--topo',         action='store', type=int,   default=None,    help="Print UVM topology at this depth.")
    p.add_argument('--wdog',         action='store', type=int,   default=None,    help="Time (in ns) at which the testbench will watchdog timeout.")
    p.add_argument('--gui',  '-g',   action='store_true',        default=False,   help="Run DVE in GUI mode.")
    p.add_argument('--wave', '-w',   action='store_true',        default=False,   help="Dump waves to VPD file.")
    p.add_argument('--svfcov',       action='store_true',        default=False,   help="Run with SV Functional Coverage")

    gvars.Options = p.parse_args()

    gadgets = gvars.Options.gadgets
    shortcuts = {
                 'c'        : 'clean',
                 'cln'      : 'clean',
                 'clean'    : 'clean',
                 'partition': 'partition',
                 'par'      : 'partition',
                 'p'        : 'partition',
                 'b'        : 'build',
                 'build'    : 'build',
                 'bld'      : 'build',
                 's'        : 'simulate',
                 'sim'      : 'simulate',
                 'simu'     : 'simulate',
                 'simulate' : 'simulate',
                 'help'     : 'help',
                 }

    for gadget in gadgets:
        if gadget not in shortcuts.keys():
            Log.critical("Unknown gadget: %s" % gadget)

    # Shortcut: just running 'gogo' will build and simulate
    if gadgets == []:
        gadgets = ['bld', 'sim']

    return [shortcuts[gadget] for gadget in gadgets]

########################################################################################
def run_build():
    import build_gadget
    for JobGadget in gvars.pre_build_gadgets:
        job = JobGadget()
        job.run()

    job = build_gadget.get_builder()()
    job.run()

    for JobGadget in gvars.post_build_gadgets:
        job = JobGadget()
        job.run()

########################################################################################
def run_simulate():
    import simulate_gadget
    job = simulate_gadget.SimulateGadget()
    job.run()

    Log.info("%s...PASSED" % job.name)
    # TODO: run simrpt?

########################################################################################
if __name__ == '__main__':
    gadgets = parse_args()
    gvars.setup_globals()

    from gadget import GadgetFailed

    try:
        if 'help' in gadgets:
            import sys
            gvars.print_keys()
            sys.exit(0)
        if 'clean' in gadgets:
            import clean_gadget
            job = clean_gadget.CleanGadget()
            job.run()
        if 'partition' in gadgets:
            import partition_gadget
            job = partition_gadget.PartitionGadget()
            job.run()
        if 'build' in gadgets:
            run_build()
        if 'simulate' in gadgets:
            run_simulate()
    except KeyboardInterrupt:
        Log.critical("Exiting due to Ctrl-C.")

    except GadgetFailed as inst:
        Log.critical("%s Failed! Cannot Continue." % inst.args[0])

    # if we get here, we must have passed
    logging.shutdown()

